# Generated by Django 3.1.7 on 2021-03-15 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='site name', max_length=150, unique=True, verbose_name='site name')),
                ('site_url', models.CharField(help_text='site url', max_length=150, unique=True, verbose_name='site url')),
                ('category', models.CharField(help_text='site url', max_length=100, unique=True, verbose_name='site url')),
            ],
        ),
    ]
