# Generated by Django 3.1.7 on 2021-03-15 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='category',
            field=models.CharField(help_text='subject of the site', max_length=100, unique=True, verbose_name='caregory'),
        ),
    ]
