# Generated by Django 3.1.7 on 2021-03-14 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResetAuth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=254)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_changed', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Reset password registers',
                'verbose_name_plural': 'Reset passwords registers',
                'db_table': 'reset_auth',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('birth_date', models.DateField(help_text='User birthday', verbose_name='User birthday')),
                ('email', models.EmailField(help_text='User email', max_length=150, unique=True, verbose_name='Email')),
                ('first_name', models.CharField(blank=True, help_text='User first name', max_length=100, verbose_name='First name')),
                ('last_name', models.CharField(blank=True, help_text='User last name', max_length=100, verbose_name='Last name')),
                ('date_joined', models.DateTimeField(auto_now_add=True, help_text='Create date of user', verbose_name='date joined')),
                ('is_active', models.BooleanField(default=False, help_text='Is user active?', verbose_name='Is user active?')),
                ('is_admin', models.BooleanField(default=False, help_text='Is user admin?', verbose_name='Is user admin?')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
