# Generated by Django 3.1.7 on 2021-03-15 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_user_birth_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='feed',
            field=models.JSONField(blank=True, default={}, help_text='You favorite sites', verbose_name='Favorite sites'),
        ),
    ]
