# Generated by Django 3.1.7 on 2021-03-16 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0003_auto_20210315_2225'),
        ('accounts', '0004_delete_resetauth'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='feed',
        ),
        migrations.AddField(
            model_name='user',
            name='feed',
            field=models.ManyToManyField(to='feed.Site'),
        ),
    ]
