# Generated by Django 3.1.7 on 2021-04-27 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20210315_2226'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='feed',
        ),
    ]
